# -------------------------------------------------------
# THE GREEN BRICK ROAD
# -------------------------------------------------------
# Copyright (c) [2023] The Green Brick Road
# All rights reserved
# -------------------------------------------------------
# Configure URLs accessible by search engine crawlers
# -------------------------------------------------------
# Nadège LEMPERIERE, @02 may 2023
# Latest revision: 02 may 2023
# -------------------------------------------------------

name: Website Build Pipeline

on: push

jobs:

    build:
        name: Build Website
        runs-on: ubuntu-latest
        container: node:alpine
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Linting code
              uses: docker://node:alpine
              continue-on-error: true
              with:
                args: npm run lint

            - name: Building application
              uses: docker://node:alpine
              with:
                args: npm run build

            - name: Run Snyk to check for vulnerabilities
              continue-on-error: true
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --sarif-file-output=snyk.sarif

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@main
              if: always()
              with:
                sarif_file: snyk.sarif

    test:
        name: Testing Website
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Launching tests
              continue-on-error: true
              uses: docker://node:alpine
              with:
                args: npm test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@main
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: clover.xml, coverage-final.json,lcov.info
                directory: ./coverage/
                name: codecov-portal
                fail_ci_if_error: true
                verbose: true
                commit_parent: ${{ github.sha }}

    publish:
        name: Publish Website
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Building application
              uses: docker://node:alpine
              with:
                args: npm run build

            - name: Publish portal to Github Pages
              uses: peaceiris/actions-gh-pages@main
              with:
                publish_dir: ./build/
                github_token: ${{ secrets.GH_ACCESS_TOKEN }}
                commit_message: "Generate Documentation"