# -------------------------------------------------------
# THE GREEN BRICK ROAD
# -------------------------------------------------------
# Copyright (c) [2023] The Green Brick Road
# All rights reserved
# -------------------------------------------------------
# Configure pipeline for each commit
# -------------------------------------------------------
# Nadège LEMPERIERE, @02 may 2023
# Latest revision: 02 may 2023
# -------------------------------------------------------

name: Website Latest Pipeline

on:
  push:
  workflow_dispatch:

jobs:

    check:
        name: Static code analysis
        runs-on: ubuntu-latest
        container: node:alpine
        permissions:
          # For CodeQL actions
          security-events: write
          actions: read
          contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Install dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Lint code
              uses: docker://node:alpine
              continue-on-error: true
              with:
                args: npm run lint

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              continue-on-error: true
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --sarif-file-output=snyk.sarif

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@main
              continue-on-error: true
              if: always()
              with:
                sarif_file: snyk.sarif

    test:
        name: Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Install dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Launch tests
              uses: docker://node:alpine
              continue-on-error: true
              with:
                args: npm test -- --watchAll=false --passWithNoTests

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@main
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: clover.xml, coverage-final.json,lcov.info
                directory: ./coverage/
                name: codecov-portal
                fail_ci_if_error: false
                verbose: true
                commit_parent: ${{ github.sha }}

    publish:
        name: Firebase publication
        runs-on: ubuntu-latest
        needs: [check, test]
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Install dependencies
              uses: docker://node:alpine
              with:
                args: npm install --omit=dev

            - name: Build application
              uses: docker://node:alpine
              with:
                args: npm run build

            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
                projectId: ${{ secrets.FIREBASE_PROJECT }}
                channelId: latest