# -------------------------------------------------------
# THE GREEN BRICK ROAD
# -------------------------------------------------------
# Copyright (c) [2023] The Green Brick Road
# All rights reserved
# -------------------------------------------------------
# Configure pipeline for regular security checks
# -------------------------------------------------------
# Nadège LEMPERIERE, @03 may 2023
# Latest revision: 03 may 2023
# -------------------------------------------------------

name: Website Regular Scan Pipeline

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:

    sast:
        name: Static code analysis
        runs-on: ubuntu-latest
        container: node:alpine
        permissions:
          # For CodeQL actions
          security-events: write
          actions: read
          contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Install dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Lint code
              uses: docker://node:alpine
              continue-on-error: true
              with:
                args: npm run lint

            - name: Build application
              uses: docker://node:alpine
              with:
                args: npm run build


            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --sarif-file-output=snyk.sarif

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@main
              if: always()
              with:
                sarif_file: snyk.sarif

    dast:
        name: Dynamic Website analysis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: zap scan
              uses: zaproxy/action-full-scan@master
              with:
                token:  ${{ secrets.GH_ACCESS_TOKEN }}
                docker_name: 'owasp/zap2docker-stable'
                target: 'https://${{ secrets.FIREBASE_PROJECT }}.web.app/'
                rules_file_name: 'rules.tsv'
                cmd_options: '-a -j'